import type { HeroClass, InventoryItem, Ruleset } from "@/types/game";

export const starterItems: InventoryItem[] = [
  {
    id: "item-healers-kit",
    name: "Healer's kit",
    rarity: "Common",
    attunement: false,
    notes: "A compact field kit for stabilizing allies.",
  },
  {
    id: "item-moonsteel-token",
    name: "Moonsteel token",
    rarity: "Uncommon",
    attunement: true,
    notes: "A cool silver charm that hums near old magic.",
  },
  {
    id: "item-ember-vial",
    name: "Ember vial",
    rarity: "Rare",
    attunement: false,
    notes: "A sealed glass vial with a coal-bright heart.",
  },
];

type RawClassLearning = {
  coreTraits: string[];
  levelProgression: Array<{
    level: number;
    features: string[];
  }>;
};

const featureDescriptions: Record<string, string> = {
  "2nd-level spells": "Your spellcasting opens into stronger utility, control, and support options.",
  "3rd-level spells": "You gain access to defining mid-tier magic with bigger combat and exploration impact.",
  "4th-level spells": "Your magic expands into more powerful protection, mobility, and control effects.",
  "5th-level spells": "You unlock high-impact spells that can reshape encounters and travel.",
  "6th-level spells": "You begin casting rare magic that can swing major scenes and boss fights.",
  "7th-level spells": "You gain advanced magic with dramatic battlefield and story consequences.",
  "8th-level spells": "Your spell list reaches near-legendary effects with broad problem-solving power.",
  "9th-level spells": "You unlock the highest tier of spells available to mortal adventurers.",
  "Ability Score Improvement":
    "You gain the Ability Score Improvement feat or another feat of your choice for which you qualify.",
  "Action Surge": "Take one additional action on your turn, giving you a burst of offense, movement, or utility.",
  "Action Surge improvement": "You can use Action Surge more often before you need a rest.",
  "Arcane Recovery": "Recover a small amount of expended spell power during a short rest.",
  "Arcane Tradition": "Choose the wizard specialty that shapes how your spell study develops.",
  "Archetype Feature": "Your chosen subclass grants a new feature or improves one of its defining tools.",
  "Aura improvements": "The reach and reliability of your paladin auras improve for nearby allies.",
  "Aura of Courage": "You and nearby allies gain protection against fear while you are conscious.",
  "Aura of Protection": "Nearby allies benefit from your Charisma when making saving throws.",
  "Bard College": "Choose the bard subclass that defines your performance style and magical focus.",
  "Bardic Inspiration": "Give an ally an inspiration die they can add to an important roll.",
  "Bardic Inspiration improvement": "Your inspiration die becomes stronger, making your support more reliable.",
  "Beast Spells": "Cast many druid spells even while using Wild Shape.",
  Blindsense: "Notice hidden or invisible creatures close to you through sharpened awareness.",
  "Brutal Critical": "Roll extra weapon damage when you score a critical hit.",
  "Brutal Critical improvement": "Your critical hits gain additional extra damage dice.",
  "Channel Divinity": "Spend divine power on a special cleric ability tied to faith and domain.",
  "Channel Divinity improvement": "You can use Channel Divinity more often before resting.",
  "Circle Feature": "Your druid circle grants a new nature-themed feature or improves an existing one.",
  "College Feature": "Your bard college grants a new specialty feature or improves its theme.",
  Countercharm: "Use performance to help allies resist charm and fear effects.",
  "Cunning Action": "Dash, Disengage, or Hide as a bonus action for sharp battlefield mobility.",
  "Danger Sense": "You are better at reacting to visible threats and sudden hazards.",
  "Deeper pact magic": "Your pact spell slots become stronger and refresh on short rests.",
  "Deflect Missiles": "Reduce incoming ranged weapon damage and potentially throw the projectile back.",
  "Destroy Undead": "When you turn weak undead, some are destroyed outright.",
  "Destroy Undead improvement": "Your Destroy Undead feature affects stronger undead creatures.",
  "Diamond Soul": "Gain broad saving throw protection and a way to reroll failed saves.",
  "Divine Domain": "Choose the cleric domain that shapes your divine powers and bonus magic.",
  "Divine Health": "Your divine power protects you from disease.",
  "Divine Intervention": "Call on your deity for direct aid in a moment of great need.",
  "Divine Intervention improvement": "Your divine aid becomes more reliable when you call for it.",
  "Divine Sense": "Sense certain supernatural creatures and consecrated or desecrated places nearby.",
  "Divine Smite": "Spend spell power to add radiant damage to a weapon hit.",
  "Domain Feature": "Your divine domain grants a new feature or improves one of its blessings.",
  "Druid Circle": "Choose the druid subclass that defines your bond with nature.",
  Druidic: "Know the secret druidic language and signs used by primal spellcasters.",
  "Eldritch Invocations": "Choose strange permanent magical gifts that customize your warlock powers.",
  "Eldritch Master": "Rapidly renew your pact magic in a critical moment.",
  Elusive: "Enemies have a much harder time gaining advantage against you.",
  "Empty Body": "Become difficult to perceive and briefly step beyond ordinary physical limits.",
  Evasion: "Avoid or reduce damage from many area effects with exceptional reflexes.",
  Expertise: "Double your proficiency bonus with selected skills or tools.",
  "Extra Attack": "Attack twice when you take the Attack action.",
  "Extra Attack improvement": "Make even more attacks when you take the Attack action.",
  "Fast Movement": "Your movement speed increases while you are not wearing heavy armor.",
  "Favored Enemy": "Become better at tracking, recalling, or confronting chosen enemy types.",
  "Favored Enemy improvement": "Expand or strengthen your favored enemy training.",
  "Feral Instinct": "React faster at the start of combat and resist being caught off guard.",
  "Feral Senses": "Fight more effectively against creatures you cannot clearly see.",
  "Fighting Style": "Choose a combat style that gives a steady bonus to how you fight.",
  "Foe Slayer": "Add extra precision against enemies you have learned to hunt.",
  "Font of Inspiration": "Recover Bardic Inspiration more quickly, making support easier to sustain.",
  "Font of Magic": "Gain sorcery points, the fuel for flexible spellcasting and metamagic.",
  "Higher-level pact magic": "Your pact magic reaches stronger spell levels while staying short-rest focused.",
  "Hide in Plain Sight": "Prepare camouflage that helps you vanish into natural surroundings.",
  "Improved Divine Smite": "Your weapon hits carry extra radiant damage without spending a spell slot.",
  Indomitable: "Reroll a failed saving throw to stay in the fight.",
  "Indomitable improvement": "Use Indomitable more often before resting.",
  "Indomitable Might": "Treat low Strength checks as stronger results while raging.",
  "Jack of All Trades": "Add part of your proficiency bonus to many checks you are not trained in.",
  Ki: "Gain a pool of focus points used for special monk techniques.",
  "Ki-Empowered Strikes": "Your unarmed strikes count as magical for overcoming resistance.",
  "Land's Stride": "Move more easily through natural terrain and resist some plant-based hindrances.",
  "Lay on Hands": "Heal wounds or cure certain conditions with a pool of divine healing.",
  "Magical Secrets": "Learn spells from outside the bard list to customize your magical toolkit.",
  "Martial Archetype": "Choose the fighter subclass that defines your combat specialty.",
  Metamagic: "Spend sorcery points to reshape how your spells behave.",
  "Metamagic option": "Learn another way to alter your spells with sorcery points.",
  "Monastic Tradition": "Choose the monk subclass that shapes your martial discipline.",
  "More invocations": "Learn additional eldritch invocations to customize your pact powers.",
  "Mystic Arcanum": "Gain a powerful once-per-day warlock spell outside normal pact slots.",
  "Mystic Arcanum improvement": "Add another high-level arcanum to your warlock magic.",
  "Natural Explorer": "Become especially capable at travel, tracking, and survival in favored terrain.",
  "Natural Explorer improvement": "Expand or strengthen your favored terrain expertise.",
  "Oath capstone": "Your sacred oath culminates in a powerful transformation or battle-defining feature.",
  "Oath Feature": "Your sacred oath grants a new feature or improves its divine theme.",
  "Origin Feature": "Your sorcerous origin grants a new feature or improves its magical theme.",
  "Otherworldly Patron": "Choose the powerful patron that grants and shapes your warlock magic.",
  "Pact Boon": "Receive a pact gift such as a blade, tome, chain, or similar defining tool.",
  "Pact Magic": "Cast a small number of potent spells that recharge on a short rest.",
  "Path Feature": "Your primal path grants a new rage-related feature or improves its theme.",
  "Patron Feature": "Your patron grants a new supernatural feature or improves its influence.",
  "Perfect Self": "Regain focus when battle starts and you are nearly spent.",
  "Persistent Rage": "Your rage becomes much harder to end before combat is done.",
  "Primal Champion": "Your Strength and Constitution rise beyond ordinary limits.",
  "Primal Path": "Choose the barbarian subclass that shapes your rage and instincts.",
  "Primeval Awareness": "Spend primal magic to sense certain creatures across the wilderness.",
  "Purity of Body": "Your disciplined body becomes immune to disease and poison.",
  Rage: "Enter a battle fury that improves melee damage and helps you resist weapon blows.",
  "Ranger Archetype": "Choose the ranger subclass that defines your hunting style.",
  "Reckless Attack": "Attack with advantage by leaving yourself easier to hit until your next turn.",
  "Relentless Rage": "When damage would drop you, attempt to stay standing instead.",
  "Reliable Talent": "Treat poor rolls on trained checks as solid results.",
  "Roguish Archetype": "Choose the rogue subclass that defines your specialty.",
  "Sacred Oath": "Swear the paladin oath that shapes your powers and principles.",
  "Second Wind": "Use a bonus action to recover hit points and keep fighting.",
  "Signature Spells": "Keep two favored spells ready and cast them with exceptional reliability.",
  "Slippery Mind": "Gain stronger mental defenses against spells and influence.",
  "Slow Fall": "Reduce falling damage by controlling your descent.",
  "Sneak Attack": "Deal extra damage when you strike with precision under the right conditions.",
  "Song of Rest": "Help allies recover extra hit points during a short rest.",
  "Song of Rest improvement": "Your restorative song heals more as your bard level rises.",
  "Sorcerous Origin": "Choose the source of your innate magic and its first benefits.",
  "Sorcerous Restoration": "Recover sorcery points when you are depleted.",
  Spellcasting: "Cast prepared or known spells using the class's spell list and spellcasting ability.",
  "Spell Mastery": "Choose low-level spells you can cast repeatedly with little effort.",
  "Stroke of Luck": "Turn a missed attack or failed ability check into success.",
  "Stunning Strike": "Spend focus to try to stun a creature you hit.",
  "Superior Inspiration": "Regain inspiration when combat begins and you have none left.",
  "Thieves' Cant": "Know secret slang and signs used by rogues and criminal networks.",
  "Timeless Body": "Age touches you less, and your body needs fewer ordinary comforts.",
  "Tongue of the Sun and Moon": "Communicate with any creature that understands a language.",
  "Tradition Feature": "Your monastic or arcane tradition grants a new specialty feature.",
  "Unarmored Defense": "Calculate defense without armor using your training and key abilities.",
  "Unarmored Movement": "Move faster while unarmored.",
  "Unarmored Movement improvement": "Your unarmored movement becomes more versatile or faster.",
  "Uncanny Dodge": "Use your reaction to reduce damage from an attack that hits you.",
  Vanish: "Hide quickly and become harder to track.",
  "Wild Shape": "Assume beast forms for scouting, utility, and combat options.",
  "Wild Shape improvement": "Use stronger or more versatile Wild Shape forms.",
  // Artificer features
  "Magical Tinkering": "Imbue a Tiny nonmagical object with a minor magical property, such as a faint glow or recorded message.",
  "Infuse Item": "Touch a nonmagical item to turn it into a temporary magic item from a known list of infusions.",
  "The Right Tool for the Job": "Rapidly create a set of artisan's tools using only thieves' tools or artisan's tools on hand.",
  "Tool Expertise": "Double your proficiency bonus for any ability check that uses a tool you are proficient with.",
  "Artificer Specialist": "Choose the artificer subclass that defines your tinkering focus and bonus spells.",
  "Flash of Genius": "Use your reaction to add your Intelligence modifier to a nearby creature's ability check or saving throw.",
  "Magic Item Adept": "Attune to more magic items than usual and craft common or uncommon items faster.",
  "Spell-Storing Item": "Store an artificer spell inside a simple object so another creature can cast it with the item.",
  "Magic Item Savant": "Attune to even more magic items and ignore most class, species, and level restrictions on them.",
  "Magic Item Master": "Attune to a large number of magic items and gain a saving throw bonus for each attuned item.",
  "Soul of Artifice": "Gain a powerful, layered defensive benefit while your attuned magic items remain active.",
  // Artificer progression spell notes
  "Tool-based spellcasting": "You must use thieves' tools, artisan's tools, or an infused item as a spellcasting focus for artificer spells.",
  "Infuse Item improvement": "You can maintain more infusions at once, and more infusion options become available.",
};

function describeFeature(name: string) {
  return (
    featureDescriptions[name] ??
    "This class feature improves or expands one of your chosen class abilities."
  );
}

const rawClassLearning: Record<string, RawClassLearning> = {
  barbarian: {
    coreTraits: [
      "Role: front-line bruiser",
      "Hit Die: d12",
      "Primary abilities: Strength and Constitution",
      "Armor: light armor, medium armor, shields",
      "Weapons: simple and martial weapons",
      "Signature rhythm: rage, reckless pressure, and huge durability",
    ],
    levelProgression: [
      { level: 1, features: ["Rage", "Unarmored Defense"] },
      { level: 2, features: ["Reckless Attack", "Danger Sense"] },
      { level: 3, features: ["Primal Path"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Extra Attack", "Fast Movement"] },
      { level: 6, features: ["Path Feature"] },
      { level: 7, features: ["Feral Instinct"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Brutal Critical"] },
      { level: 10, features: ["Path Feature"] },
      { level: 11, features: ["Relentless Rage"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Brutal Critical improvement"] },
      { level: 14, features: ["Path Feature"] },
      { level: 15, features: ["Persistent Rage"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Brutal Critical improvement"] },
      { level: 18, features: ["Indomitable Might"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Primal Champion"] },
    ],
  },
  bard: {
    coreTraits: [
      "Role: support caster and skill expert",
      "Hit Die: d8",
      "Primary abilities: Charisma and Dexterity",
      "Armor: light armor",
      "Weapons: simple weapons, hand crossbows, rapiers, shortswords",
      "Signature rhythm: inspiration, flexible magic, and social control",
    ],
    levelProgression: [
      { level: 1, features: ["Spellcasting", "Bardic Inspiration"] },
      { level: 2, features: ["Jack of All Trades", "Song of Rest"] },
      { level: 3, features: ["Bard College", "Expertise"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Font of Inspiration", "Bardic Inspiration improvement"] },
      { level: 6, features: ["Countercharm", "College Feature"] },
      { level: 7, features: ["4th-level spells"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Song of Rest improvement"] },
      { level: 10, features: ["Magical Secrets", "Expertise", "Bardic Inspiration improvement"] },
      { level: 11, features: ["6th-level spells"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Song of Rest improvement"] },
      { level: 14, features: ["Magical Secrets", "College Feature"] },
      { level: 15, features: ["Bardic Inspiration improvement"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Song of Rest improvement"] },
      { level: 18, features: ["Magical Secrets"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Superior Inspiration"] },
    ],
  },
  cleric: {
    coreTraits: [
      "Role: divine caster, healer, and armored support",
      "Hit Die: d8",
      "Primary ability: Wisdom",
      "Armor: light armor, medium armor, shields",
      "Weapons: simple weapons",
      "Signature rhythm: prepared divine spells, domain powers, and party recovery",
    ],
    levelProgression: [
      { level: 1, features: ["Spellcasting", "Divine Domain"] },
      { level: 2, features: ["Channel Divinity"] },
      { level: 3, features: ["2nd-level spells"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["3rd-level spells", "Destroy Undead"] },
      { level: 6, features: ["Domain Feature", "Channel Divinity improvement"] },
      { level: 7, features: ["4th-level spells"] },
      { level: 8, features: ["Ability Score Improvement", "Domain Feature"] },
      { level: 9, features: ["5th-level spells"] },
      { level: 10, features: ["Divine Intervention"] },
      { level: 11, features: ["Destroy Undead improvement"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["7th-level spells"] },
      { level: 14, features: ["Destroy Undead improvement"] },
      { level: 15, features: ["8th-level spells"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Domain Feature", "Destroy Undead improvement"] },
      { level: 18, features: ["Channel Divinity improvement"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Divine Intervention improvement"] },
    ],
  },
  druid: {
    coreTraits: [
      "Role: primal caster, controller, and shapeshifter",
      "Hit Die: d8",
      "Primary abilities: Wisdom and Constitution",
      "Armor: light armor, medium armor, shields",
      "Weapons: druidic and simple weapon training",
      "Signature rhythm: prepared nature magic, battlefield control, and wild forms",
    ],
    levelProgression: [
      { level: 1, features: ["Druidic", "Spellcasting"] },
      { level: 2, features: ["Wild Shape", "Druid Circle"] },
      { level: 3, features: ["2nd-level spells"] },
      { level: 4, features: ["Ability Score Improvement", "Wild Shape improvement"] },
      { level: 5, features: ["3rd-level spells"] },
      { level: 6, features: ["Circle Feature"] },
      { level: 7, features: ["4th-level spells"] },
      { level: 8, features: ["Ability Score Improvement", "Wild Shape improvement"] },
      { level: 9, features: ["5th-level spells"] },
      { level: 10, features: ["Circle Feature"] },
      { level: 11, features: ["6th-level spells"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["7th-level spells"] },
      { level: 14, features: ["Circle Feature"] },
      { level: 15, features: ["8th-level spells"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["9th-level spells"] },
      { level: 18, features: ["Timeless Body", "Beast Spells"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Archdruid"] },
    ],
  },
  fighter: {
    coreTraits: [
      "Role: weapon specialist and flexible combat anchor",
      "Hit Die: d10",
      "Primary abilities: Strength or Dexterity",
      "Armor: all armor and shields",
      "Weapons: simple and martial weapons",
      "Signature rhythm: fighting style, extra attacks, and reliable action economy",
    ],
    levelProgression: [
      { level: 1, features: ["Fighting Style", "Second Wind"] },
      { level: 2, features: ["Action Surge"] },
      { level: 3, features: ["Martial Archetype"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Extra Attack"] },
      { level: 6, features: ["Ability Score Improvement"] },
      { level: 7, features: ["Archetype Feature"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Indomitable"] },
      { level: 10, features: ["Archetype Feature"] },
      { level: 11, features: ["Extra Attack improvement"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Indomitable improvement"] },
      { level: 14, features: ["Ability Score Improvement"] },
      { level: 15, features: ["Archetype Feature"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Action Surge improvement", "Indomitable improvement"] },
      { level: 18, features: ["Archetype Feature"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Extra Attack improvement"] },
    ],
  },
  monk: {
    coreTraits: [
      "Role: mobile striker and defensive skirmisher",
      "Hit Die: d8",
      "Primary abilities: Dexterity and Wisdom",
      "Armor: usually unarmored",
      "Weapons: simple weapons and shortswords",
      "Signature rhythm: martial arts, focus-powered maneuvers, and speed",
    ],
    levelProgression: [
      { level: 1, features: ["Unarmored Defense", "Martial Arts"] },
      { level: 2, features: ["Ki", "Unarmored Movement"] },
      { level: 3, features: ["Monastic Tradition", "Deflect Missiles"] },
      { level: 4, features: ["Ability Score Improvement", "Slow Fall"] },
      { level: 5, features: ["Extra Attack", "Stunning Strike"] },
      { level: 6, features: ["Ki-Empowered Strikes", "Tradition Feature"] },
      { level: 7, features: ["Evasion", "Stillness of Mind"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Unarmored Movement improvement"] },
      { level: 10, features: ["Purity of Body"] },
      { level: 11, features: ["Tradition Feature"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Tongue of the Sun and Moon"] },
      { level: 14, features: ["Diamond Soul"] },
      { level: 15, features: ["Timeless Body"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Tradition Feature"] },
      { level: 18, features: ["Empty Body"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Perfect Self"] },
    ],
  },
  paladin: {
    coreTraits: [
      "Role: armored defender, striker, and divine support",
      "Hit Die: d10",
      "Primary abilities: Strength and Charisma",
      "Armor: all armor and shields",
      "Weapons: simple and martial weapons",
      "Signature rhythm: auras, smites, healing, and oath powers",
    ],
    levelProgression: [
      { level: 1, features: ["Divine Sense", "Lay on Hands"] },
      { level: 2, features: ["Fighting Style", "Spellcasting", "Divine Smite"] },
      { level: 3, features: ["Divine Health", "Sacred Oath"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Extra Attack", "2nd-level spells"] },
      { level: 6, features: ["Aura of Protection"] },
      { level: 7, features: ["Oath Feature"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["3rd-level spells"] },
      { level: 10, features: ["Aura of Courage"] },
      { level: 11, features: ["Improved Divine Smite"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["4th-level spells"] },
      { level: 14, features: ["Cleansing Touch"] },
      { level: 15, features: ["Oath Feature"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["5th-level spells"] },
      { level: 18, features: ["Aura improvements"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Oath capstone"] },
    ],
  },
  ranger: {
    coreTraits: [
      "Role: scout, striker, and wilderness guide",
      "Hit Die: d10",
      "Primary abilities: Dexterity and Wisdom",
      "Armor: light armor, medium armor, shields",
      "Weapons: simple and martial weapons",
      "Signature rhythm: tracking, ranged pressure, and primal utility magic",
    ],
    levelProgression: [
      { level: 1, features: ["Favored Enemy", "Natural Explorer"] },
      { level: 2, features: ["Fighting Style", "Spellcasting"] },
      { level: 3, features: ["Ranger Archetype", "Primeval Awareness"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Extra Attack"] },
      { level: 6, features: ["Favored Enemy improvement", "Natural Explorer improvement"] },
      { level: 7, features: ["Archetype Feature"] },
      { level: 8, features: ["Ability Score Improvement", "Land's Stride"] },
      { level: 9, features: ["3rd-level spells"] },
      { level: 10, features: ["Natural Explorer improvement", "Hide in Plain Sight"] },
      { level: 11, features: ["Archetype Feature"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["4th-level spells"] },
      { level: 14, features: ["Favored Enemy improvement", "Vanish"] },
      { level: 15, features: ["Archetype Feature"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["5th-level spells"] },
      { level: 18, features: ["Feral Senses"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Foe Slayer"] },
    ],
  },
  rogue: {
    coreTraits: [
      "Role: infiltrator, skill expert, and precision striker",
      "Hit Die: d8",
      "Primary ability: Dexterity",
      "Armor: light armor",
      "Weapons: finesse weapons, simple weapons, and thieves' tools",
      "Signature rhythm: expertise, mobility, sneak attack, and avoiding harm",
    ],
    levelProgression: [
      { level: 1, features: ["Expertise", "Sneak Attack", "Thieves' Cant"] },
      { level: 2, features: ["Cunning Action"] },
      { level: 3, features: ["Roguish Archetype"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Uncanny Dodge"] },
      { level: 6, features: ["Expertise"] },
      { level: 7, features: ["Evasion"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Archetype Feature"] },
      { level: 10, features: ["Ability Score Improvement"] },
      { level: 11, features: ["Reliable Talent"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Archetype Feature"] },
      { level: 14, features: ["Blindsense"] },
      { level: 15, features: ["Slippery Mind"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Archetype Feature"] },
      { level: 18, features: ["Elusive"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Stroke of Luck"] },
    ],
  },
  sorcerer: {
    coreTraits: [
      "Role: innate arcane caster and burst specialist",
      "Hit Die: d6",
      "Primary abilities: Charisma and Constitution",
      "Armor: no armor by default",
      "Weapons: daggers, quarterstaffs, and light crossbows",
      "Signature rhythm: spontaneous magic, sorcery points, and metamagic",
    ],
    levelProgression: [
      { level: 1, features: ["Spellcasting", "Sorcerous Origin"] },
      { level: 2, features: ["Font of Magic"] },
      { level: 3, features: ["Metamagic"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["3rd-level spells"] },
      { level: 6, features: ["Origin Feature"] },
      { level: 7, features: ["4th-level spells"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["5th-level spells"] },
      { level: 10, features: ["Metamagic option"] },
      { level: 11, features: ["6th-level spells"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["7th-level spells"] },
      { level: 14, features: ["Origin Feature"] },
      { level: 15, features: ["8th-level spells"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["9th-level spells", "Metamagic option"] },
      { level: 18, features: ["Origin Feature"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Sorcerous Restoration"] },
    ],
  },
  warlock: {
    coreTraits: [
      "Role: pact caster with reliable magical pressure",
      "Hit Die: d8",
      "Primary abilities: Charisma and Constitution",
      "Armor: light armor",
      "Weapons: simple weapons",
      "Signature rhythm: pact magic, invocations, and patron gifts",
    ],
    levelProgression: [
      { level: 1, features: ["Otherworldly Patron", "Pact Magic"] },
      { level: 2, features: ["Eldritch Invocations"] },
      { level: 3, features: ["Pact Boon"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["Deeper pact magic", "More invocations"] },
      { level: 6, features: ["Patron Feature"] },
      { level: 7, features: ["More invocations"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["Higher-level pact magic"] },
      { level: 10, features: ["Patron Feature"] },
      { level: 11, features: ["Mystic Arcanum"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["Mystic Arcanum improvement"] },
      { level: 14, features: ["Patron Feature"] },
      { level: 15, features: ["Mystic Arcanum improvement"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["Mystic Arcanum improvement"] },
      { level: 18, features: ["More invocations"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Eldritch Master"] },
    ],
  },
  wizard: {
    coreTraits: [
      "Role: prepared arcane caster and utility specialist",
      "Hit Die: d6",
      "Primary ability: Intelligence",
      "Armor: no armor by default",
      "Weapons: daggers, quarterstaffs, and light crossbows",
      "Signature rhythm: spellbook preparation, ritual options, and broad spell access",
    ],
    levelProgression: [
      { level: 1, features: ["Spellcasting", "Arcane Recovery"] },
      { level: 2, features: ["Arcane Tradition"] },
      { level: 3, features: ["2nd-level spells"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["3rd-level spells"] },
      { level: 6, features: ["Tradition Feature"] },
      { level: 7, features: ["4th-level spells"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["5th-level spells"] },
      { level: 10, features: ["Tradition Feature"] },
      { level: 11, features: ["6th-level spells"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["7th-level spells"] },
      { level: 14, features: ["Tradition Feature"] },
      { level: 15, features: ["8th-level spells"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["9th-level spells"] },
      { level: 18, features: ["Spell Mastery"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Signature Spells"] },
    ],
  },
  artificer: {
    coreTraits: [
      "Role: half-caster inventor and magical crafter",
      "Hit Die: d8",
      "Primary abilities: Intelligence and Constitution",
      "Armor: light armor, medium armor, shields",
      "Weapons: simple weapons, firearms if available",
      "Signature rhythm: infused items, tool-based casting, and flexible support",
    ],
    levelProgression: [
      { level: 1, features: ["Spellcasting", "Magical Tinkering"] },
      { level: 2, features: ["Infuse Item"] },
      { level: 3, features: ["Artificer Specialist", "The Right Tool for the Job"] },
      { level: 4, features: ["Ability Score Improvement"] },
      { level: 5, features: ["2nd-level spells"] },
      { level: 6, features: ["Tool Expertise", "Infuse Item improvement"] },
      { level: 7, features: ["Flash of Genius"] },
      { level: 8, features: ["Ability Score Improvement"] },
      { level: 9, features: ["3rd-level spells"] },
      { level: 10, features: ["Magic Item Adept", "Infuse Item improvement"] },
      { level: 11, features: ["Spell-Storing Item"] },
      { level: 12, features: ["Ability Score Improvement"] },
      { level: 13, features: ["4th-level spells"] },
      { level: 14, features: ["Magic Item Savant", "Infuse Item improvement"] },
      { level: 15, features: ["Specialist Feature"] },
      { level: 16, features: ["Ability Score Improvement"] },
      { level: 17, features: ["5th-level spells"] },
      { level: 18, features: ["Magic Item Master", "Infuse Item improvement"] },
      { level: 19, features: ["Ability Score Improvement"] },
      { level: 20, features: ["Soul of Artifice"] },
    ],
  },
};

const classLearning = Object.fromEntries(
  Object.entries(rawClassLearning).map(([classId, guide]) => [
    classId,
    {
      coreTraits: guide.coreTraits,
      levelProgression: guide.levelProgression.map((entry) => ({
        level: entry.level,
        features: entry.features.map((name) => ({
          name,
          description: describeFeature(name),
        })),
      })),
    },
  ]),
) as Record<string, Pick<HeroClass, "coreTraits" | "levelProgression">>;

function speciesTrait(name: string, description: string) {
  return { name, description };
}

export const ruleset: Ruleset = {
  alignments: [
    "Lawful Good",
    "Neutral Good",
    "Chaotic Good",
    "Lawful Neutral",
    "Neutral",
    "Chaotic Neutral",
    "Lawful Evil",
    "Neutral Evil",
    "Chaotic Evil",
  ],
  backgrounds: [
    "Custom Background",
    "Acolyte",
    "Criminal",
    "Sage",
    "Soldier",
  ],
  races: [
    {
      id: "dragonborn",
      name: "Dragonborn",
      sourceBook: "Player’s Handbook",
      summary: "Draconic heroes with elemental breath and a proud, striking presence.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Draconic Ancestry", "Choose a dragon lineage that shapes your breath energy and resistance."),
        speciesTrait("Breath Weapon", "Exhale elemental force in a short burst for area damage."),
        speciesTrait("Damage Resistance", "Resist the damage type tied to your draconic ancestry."),
      ],
    },
    {
      id: "dwarf",
      name: "Dwarf",
      sourceBook: "Player’s Handbook",
      summary: "Hardy delvers with steady nerves and a gift for surviving trouble.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in dim light and darkness better than most surface folk."),
        speciesTrait("Dwarven Resilience", "Resist poison and recover from toxic threats more reliably."),
        speciesTrait("Stonecunning", "Read stonework, old masonry, and underground craft with practiced eyes."),
      ],
    },
    {
      id: "elf",
      name: "Elf",
      sourceBook: "Player’s Handbook",
      summary: "Keen-eyed wanderers with quick reflexes and old-world grace.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See through darkness with a hint of old fey perception."),
        speciesTrait("Fey Ancestry", "Resist charm effects and magical sleep more easily."),
        speciesTrait("Trance", "Rest through a brief meditative state rather than ordinary sleep."),
      ],
    },
    {
      id: "gnome",
      name: "Gnome",
      sourceBook: "Player’s Handbook",
      summary: "Bright, curious folk with quick minds and a talent for clever magic.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in dim light and darkness while exploring hidden places."),
        speciesTrait("Gnomish Cunning", "Resist many magical assaults against your mind."),
        speciesTrait("Inventive Spark", "Lean into clever tricks, minor magic, and quick problem-solving."),
      ],
    },
    {
      id: "goliath",
      name: "Goliath",
      sourceBook: "Player’s Handbook",
      summary: "Powerfully built mountain-born heroes known for endurance and daring.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "35 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Giant Ancestry", "Choose a giant lineage that grants a defining physical gift."),
        speciesTrait("Powerful Build", "Carry, push, drag, and lift as though you were larger."),
        speciesTrait("Mountain Born", "Endure harsh climbs, hard travel, and punishing environments."),
      ],
    },
    {
      id: "halfling",
      name: "Halfling",
      sourceBook: "Player’s Handbook",
      summary: "Small, quick, lucky heroes who thrive under pressure.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Lucky", "Turn an unlucky moment into another chance when fortune matters."),
        speciesTrait("Brave", "Resist fear with surprising steadiness."),
        speciesTrait("Nimble", "Move through tight spaces and around larger creatures with ease."),
      ],
    },
    {
      id: "human",
      name: "Human",
      sourceBook: "Player’s Handbook",
      summary: "Adaptable, ambitious, and excellent at filling any party gap.",
      creatureType: "Humanoid",
      size: "Medium or Small",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Resourceful", "Bring extra flexibility to skills, tools, or feats."),
        speciesTrait("Skillful", "Pick up useful training that reflects your upbringing."),
        speciesTrait("Versatile", "Fit smoothly into almost any class or party role."),
      ],
    },
    {
      id: "orc",
      name: "Orc",
      sourceBook: "Player’s Handbook",
      summary: "Forceful, tireless adventurers with fierce momentum and survival instinct.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Adrenaline Rush", "Surge forward with temporary durability when the fight begins."),
        speciesTrait("Powerful Build", "Handle heavy loads and physical obstacles with ease."),
        speciesTrait("Relentless Endurance", "Stay standing when a blow would otherwise drop you."),
      ],
    },
    {
      id: "tiefling",
      name: "Tiefling",
      sourceBook: "Player’s Handbook",
      summary: "Mortals touched by lower-plane power, carrying innate magic and resistance.",
      creatureType: "Humanoid",
      size: "Medium or Small",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in gloom with supernatural clarity."),
        speciesTrait("Fiendish Legacy", "Gain innate magic shaped by an infernal, abyssal, or chthonic legacy."),
        speciesTrait("Otherworldly Resistance", "Resist a damage type tied to your fiendish heritage."),
      ],
    },
    {
      id: "dragonborn-legacy",
      name: "Dragonborn",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A 2014 dragonborn option with draconic ancestry and elemental breath.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Draconic Ancestry", "Choose a dragon type that determines breath damage and resistance."),
        speciesTrait("Breath Weapon", "Release a line or cone of elemental energy."),
        speciesTrait("Damage Resistance", "Resist the damage type associated with your ancestry."),
      ],
    },
    {
      id: "dwarf-legacy",
      name: "Dwarf (2)",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "Legacy dwarf options representing hill and mountain traditions.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "25 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See underground and in darkness more easily."),
        speciesTrait("Dwarven Resilience", "Resist poison and recover from it more reliably."),
        speciesTrait("Dwarven Combat Training", "Carry traditional weapon training from dwarf culture."),
      ],
    },
    {
      id: "elf-legacy",
      name: "Elf (3)",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "Legacy elf options representing high, wood, and drow traditions.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in dim light and darkness with elven senses."),
        speciesTrait("Fey Ancestry", "Resist charm effects and magical sleep."),
        speciesTrait("Subrace Legacy", "Choose a legacy elven tradition with its own magic, speed, or training."),
      ],
    },
    {
      id: "half-elf-legacy",
      name: "Half-Elf",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A legacy option blending human adaptability with elven grace.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in dim light and darkness with elven influence."),
        speciesTrait("Fey Ancestry", "Resist charm effects and magical sleep."),
        speciesTrait("Skill Versatility", "Gain flexible extra training from a blended heritage."),
      ],
    },
    {
      id: "half-orc-legacy",
      name: "Half-Orc",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A legacy option with fierce endurance and punishing critical strikes.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in darkness with orcish senses."),
        speciesTrait("Relentless Endurance", "Avoid falling when a hit would drop you to zero."),
        speciesTrait("Savage Attacks", "Deal extra weapon damage on a critical hit."),
      ],
    },
    {
      id: "halfling-legacy",
      name: "Halfling (2)",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "Legacy halfling options representing lightfoot and stout families.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "25 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Lucky", "Reroll a bad d20 moment and try for better fortune."),
        speciesTrait("Brave", "Stand firm against frightening effects."),
        speciesTrait("Halfling Nimbleness", "Move through the space of larger creatures."),
      ],
    },
    {
      id: "human-legacy",
      name: "Human (2)",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "Legacy human options covering standard and variant human builds.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Adaptable", "Spread improvements broadly or focus into a feat-based variant."),
        speciesTrait("Extra Training", "Variant builds begin with additional skill and feat flexibility."),
        speciesTrait("Broad Culture", "Fit nearly any origin, class, or campaign style."),
      ],
    },
    {
      id: "rock-gnome-legacy",
      name: "Rock Gnome",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A legacy gnome option focused on craft, curiosity, and clever devices.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "25 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in the dark with gnomish eyes."),
        speciesTrait("Gnome Cunning", "Resist many magic effects that target your mind."),
        speciesTrait("Artificer's Lore", "Recognize magical, alchemical, and mechanical craftsmanship."),
      ],
    },
    {
      id: "tiefling-legacy",
      name: "Tiefling",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A legacy tiefling option with infernal resistance and innate magic.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See through dim light and darkness."),
        speciesTrait("Hellish Resistance", "Resist fire damage."),
        speciesTrait("Infernal Legacy", "Gain a small suite of innate infernal magic."),
      ],
    },
    {
      id: "variant-aasimar",
      name: "Variant Aasimar",
      sourceBook: "Dungeon Master’s Guide (2014)",
      sourceLabel: "Legacy",
      summary: "A celestial-touched variant with radiant gifts and otherworldly presence.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Celestial Resistance", "Resist radiant and necrotic forces."),
        speciesTrait("Healing Hands", "Restore a small amount of health with a celestial touch."),
        speciesTrait("Light Bearer", "Carry a spark of innate radiant magic."),
      ],
    },
    {
      id: "aarakocra-legacy",
      name: "Aarakocra",
      sourceBook: "Elemental Evil Player's Companion",
      sourceLabel: "Legacy",
      summary: "Avian elemental wanderers built for aerial scouting and swift movement.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "25 ft., fly 50 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Flight", "Fly when not restricted by armor or circumstances that prevent it."),
        speciesTrait("Talons", "Use natural talons as a close-range weapon."),
        speciesTrait("Wind-Born", "Fit stories tied to air, high places, and elemental travel."),
      ],
    },
    {
      id: "deep-gnome-legacy",
      name: "Deep Gnome",
      sourceBook: "Elemental Evil Player's Companion",
      sourceLabel: "Legacy",
      summary: "Underground gnomes with stealthy instincts and deep-earth resilience.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "25 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Superior Darkvision", "See much farther in darkness than most creatures."),
        speciesTrait("Gnome Cunning", "Resist magic that attacks your mind."),
        speciesTrait("Stone Camouflage", "Hide more effectively among rocky surroundings."),
      ],
    },
    {
      id: "forest-gnome-legacy",
      name: "Forest Gnome",
      sourceBook: "Basic Rules (2014)",
      sourceLabel: "Legacy",
      summary: "A legacy gnome option blending woodland stealth, natural illusion, and small-creature speech.",
      creatureType: "Humanoid",
      size: "Small",
      speed: "25 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Darkvision", "See in the dark with gnomish eyes."),
        speciesTrait("Gnome Cunning", "Resist many magic effects that target your mind."),
        speciesTrait("Natural Illusionist", "Cast a simple illusion and speak with small woodland creatures."),
      ],
    },
    {
      id: "genasi-legacy",
      name: "Genasi (4)",
      sourceBook: "Elemental Evil Player's Companion",
      sourceLabel: "Legacy",
      summary: "Elemental-blooded adventurers with air, earth, fire, or water expressions.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Elemental Lineage", "Choose air, earth, fire, or water to shape your traits."),
        speciesTrait("Elemental Resistance", "Gain protection or utility tied to your elemental heritage."),
        speciesTrait("Innate Elemental Magic", "Use a small magical gift connected to your element."),
      ],
    },
    {
      id: "goliath-legacy",
      name: "Goliath",
      sourceBook: "Elemental Evil Player's Companion",
      sourceLabel: "Legacy",
      summary: "Legacy mountain folk known for athletic power and shrugging off punishment.",
      creatureType: "Humanoid",
      size: "Medium",
      speed: "30 ft.",
      bonuses: {},
      traits: [
        speciesTrait("Natural Athlete", "Excel at climbing, leaping, and feats of raw physical effort."),
        speciesTrait("Stone's Endurance", "Reduce incoming damage with stubborn toughness."),
        speciesTrait("Powerful Build", "Carry and move heavy loads as though larger."),
      ],
    },
  ],
  classes: [
    {
      id: "barbarian",
      name: "Barbarian",
      sourceBook: "Player’s Handbook",
      summary: "A primal warrior who turns rage into raw staying power.",
      ...classLearning.barbarian,
      hitDie: 12,
      primary: ["strength", "constitution"],
      proficiencies: ["Light armor", "Medium armor", "Shields", "Simple weapons", "Martial weapons"],
      startingGear: ["Greataxe", "Handaxes", "Explorer's pack"],
      actions: [
        {
          name: "Greataxe",
          ability: "strength",
          formula: "1d12 + STR",
          damageType: "Slashing",
        },
        {
          name: "Rage strike",
          ability: "strength",
          formula: "Weapon + STR + Rage",
          damageType: "Primal",
        },
      ],
      spellSuggestions: [],
      casterType: "none",
      asiLevels: [4,8,12,16,19],
    },
    {
      id: "bard",
      name: "Bard",
      sourceBook: "Player’s Handbook",
      summary: "A charismatic performer who blends magic, skill, and inspiration.",
      ...classLearning.bard,
      hitDie: 8,
      primary: ["charisma", "dexterity"],
      proficiencies: ["Light armor", "Simple weapons", "Hand crossbows", "Musical instruments"],
      startingGear: ["Rapier", "Lute", "Diplomat's pack"],
      actions: [
        {
          name: "Rapier",
          ability: "dexterity",
          formula: "1d8 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Vicious mockery",
          ability: "charisma",
          formula: "WIS save vs CHA",
          damageType: "Psychic",
        },
      ],
      spellSuggestions: ["guidance", "healing-word"],
      casterType: "full",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "charisma",
    },
    {
      id: "cleric",
      name: "Cleric",
      sourceBook: "Player’s Handbook",
      summary: "A divine caster with armor, recovery magic, and steady party support.",
      ...classLearning.cleric,
      hitDie: 8,
      primary: ["wisdom"],
      proficiencies: ["Light armor", "Medium armor", "Shields", "Simple weapons"],
      startingGear: ["Mace", "Scale mail", "Holy symbol"],
      actions: [
        {
          name: "Mace",
          ability: "strength",
          formula: "1d6 + STR",
          damageType: "Bludgeoning",
        },
        {
          name: "Sacred flame",
          ability: "wisdom",
          formula: "DEX save vs WIS",
          damageType: "Radiant",
        },
      ],
      spellSuggestions: ["guidance", "healing-word", "bless"],
      casterType: "full",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "wisdom",
    },
    {
      id: "druid",
      name: "Druid",
      sourceBook: "Player’s Handbook",
      summary: "A nature-bound spellcaster who channels wilderness and transformation.",
      ...classLearning.druid,
      hitDie: 8,
      primary: ["wisdom", "constitution"],
      proficiencies: ["Light armor", "Medium armor", "Shields", "Druidic focus"],
      startingGear: ["Scimitar", "Leather armor", "Druidic focus"],
      actions: [
        {
          name: "Scimitar",
          ability: "dexterity",
          formula: "1d6 + DEX",
          damageType: "Slashing",
        },
        {
          name: "Thorn whip",
          ability: "wisdom",
          formula: "1d6",
          damageType: "Piercing",
        },
      ],
      spellSuggestions: ["guidance", "healing-word"],
      casterType: "full",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "wisdom",
    },
    {
      id: "fighter",
      name: "Fighter",
      sourceBook: "Player’s Handbook",
      summary: "A front-line weapon expert with flexible combat pressure.",
      ...classLearning.fighter,
      hitDie: 10,
      primary: ["strength", "dexterity"],
      proficiencies: ["All armor", "Shields", "Simple weapons", "Martial weapons"],
      startingGear: ["Longsword", "Shield", "Explorer's pack"],
      actions: [
        {
          name: "Longsword",
          ability: "strength",
          formula: "1d8 + STR",
          damageType: "Slashing",
        },
        {
          name: "Heavy crossbow",
          ability: "dexterity",
          formula: "1d10 + DEX",
          damageType: "Piercing",
        },
      ],
      spellSuggestions: [],
      casterType: "none",
      asiLevels: [4,6,8,12,14,16,19],
    },
    {
      id: "monk",
      name: "Monk",
      sourceBook: "Player’s Handbook",
      summary: "A disciplined martial artist built around speed, focus, and precision.",
      ...classLearning.monk,
      hitDie: 8,
      primary: ["dexterity", "wisdom"],
      proficiencies: ["Simple weapons", "Shortswords", "Artisan's tools"],
      startingGear: ["Shortsword", "Dungeoneer's pack", "Darts"],
      actions: [
        {
          name: "Unarmed strike",
          ability: "dexterity",
          formula: "1d4 + DEX",
          damageType: "Bludgeoning",
        },
        {
          name: "Shortsword",
          ability: "dexterity",
          formula: "1d6 + DEX",
          damageType: "Piercing",
        },
      ],
      spellSuggestions: [],
      casterType: "none",
      asiLevels: [4,8,12,16,19],
    },
    {
      id: "paladin",
      name: "Paladin",
      sourceBook: "Player’s Handbook",
      summary: "A sworn champion who blends martial strength with divine power.",
      ...classLearning.paladin,
      hitDie: 10,
      primary: ["strength", "charisma"],
      proficiencies: ["All armor", "Shields", "Simple weapons", "Martial weapons"],
      startingGear: ["Longsword", "Shield", "Holy symbol"],
      actions: [
        {
          name: "Longsword",
          ability: "strength",
          formula: "1d8 + STR",
          damageType: "Slashing",
        },
        {
          name: "Divine smite",
          ability: "strength",
          formula: "Weapon + radiant",
          damageType: "Radiant",
        },
      ],
      spellSuggestions: ["bless", "healing-word"],
      casterType: "half",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "charisma",
    },
    {
      id: "ranger",
      name: "Ranger",
      sourceBook: "Player’s Handbook",
      summary: "A wilderness scout who mixes combat skill, tracking, and primal magic.",
      ...classLearning.ranger,
      hitDie: 10,
      primary: ["dexterity", "wisdom"],
      proficiencies: ["Light armor", "Medium armor", "Shields", "Martial weapons"],
      startingGear: ["Longbow", "Shortswords", "Explorer's pack"],
      actions: [
        {
          name: "Longbow",
          ability: "dexterity",
          formula: "1d8 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Shortsword",
          ability: "dexterity",
          formula: "1d6 + DEX",
          damageType: "Piercing",
        },
      ],
      spellSuggestions: ["guidance"],
      casterType: "half",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "wisdom",
    },
    {
      id: "rogue",
      name: "Rogue",
      sourceBook: "Player’s Handbook",
      summary: "A precise infiltrator built around mobility, expertise, and burst damage.",
      ...classLearning.rogue,
      hitDie: 8,
      primary: ["dexterity"],
      proficiencies: ["Light armor", "Simple weapons", "Hand crossbows", "Thieves' tools"],
      startingGear: ["Rapier", "Shortbow", "Burglar's pack"],
      actions: [
        {
          name: "Rapier",
          ability: "dexterity",
          formula: "1d8 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Sneak strike",
          ability: "dexterity",
          formula: "1d8 + DEX + 1d6",
          damageType: "Precision",
        },
      ],
      spellSuggestions: [],
      casterType: "none",
      asiLevels: [4,8,10,12,16,19],
    },
    {
      id: "sorcerer",
      name: "Sorcerer",
      sourceBook: "Player’s Handbook",
      summary: "An innate arcane caster whose magic comes from bloodline, spark, or soul.",
      ...classLearning.sorcerer,
      hitDie: 6,
      primary: ["charisma", "constitution"],
      proficiencies: ["Daggers", "Quarterstaffs", "Light crossbows"],
      startingGear: ["Light crossbow", "Component pouch", "Explorer's pack"],
      actions: [
        {
          name: "Light crossbow",
          ability: "dexterity",
          formula: "1d8 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Fire bolt",
          ability: "charisma",
          formula: "1d10",
          damageType: "Fire",
        },
      ],
      spellSuggestions: ["mage-hand", "magic-missile", "shield"],
      casterType: "full",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "charisma",
    },
    {
      id: "warlock",
      name: "Warlock",
      sourceBook: "Player’s Handbook",
      summary: "A pact-bound caster with strange gifts and reliable eldritch power.",
      ...classLearning.warlock,
      hitDie: 8,
      primary: ["charisma", "constitution"],
      proficiencies: ["Light armor", "Simple weapons"],
      startingGear: ["Light crossbow", "Arcane focus", "Scholar's pack"],
      actions: [
        {
          name: "Dagger",
          ability: "dexterity",
          formula: "1d4 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Eldritch blast",
          ability: "charisma",
          formula: "1d10",
          damageType: "Force",
        },
      ],
      spellSuggestions: ["mage-hand", "shield"],
      casterType: "pact",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "charisma",
    },
    {
      id: "wizard",
      name: "Wizard",
      sourceBook: "Player’s Handbook",
      summary: "A studied arcane caster with flexible spells and fragile defenses.",
      ...classLearning.wizard,
      hitDie: 6,
      primary: ["intelligence"],
      proficiencies: ["Daggers", "Quarterstaffs", "Light crossbows"],
      startingGear: ["Quarterstaff", "Spellbook", "Scholar's pack"],
      actions: [
        {
          name: "Quarterstaff",
          ability: "strength",
          formula: "1d6 + STR",
          damageType: "Bludgeoning",
        },
        {
          name: "Fire bolt",
          ability: "intelligence",
          formula: "1d10",
          damageType: "Fire",
        },
      ],
      spellSuggestions: ["mage-hand", "magic-missile", "shield"],
      casterType: "full",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "intelligence",
    },
    {
      id: "artificer",
      name: "Artificer",
      sourceBook: "Tasha's Cauldron of Everything",
      summary: "An inventive half-caster who weaves magic through tools, infusions, and clever craftsmanship.",
      ...classLearning.artificer,
      hitDie: 8,
      primary: ["intelligence", "constitution"],
      proficiencies: ["Light armor", "Medium armor", "Shields", "Simple weapons", "Thieves' tools", "Tinker's tools"],
      startingGear: ["Light crossbow", "Thieves' tools", "Dungeoneer's pack"],
      actions: [
        {
          name: "Light crossbow",
          ability: "dexterity",
          formula: "1d8 + DEX",
          damageType: "Piercing",
        },
        {
          name: "Fire bolt",
          ability: "intelligence",
          formula: "1d10",
          damageType: "Fire",
        },
      ],
      spellSuggestions: ["guidance", "cure-wounds", "magic-stone"],
      casterType: "half",
      asiLevels: [4,8,12,16,19],
      spellcastingAbility: "intelligence",
      subclassLevel: 3,
    },
  ],
  spells: [
    {
      id: "guidance",
      name: "Guidance",
      level: 0,
      school: "Divination",
      action: "Action",
      summary: "Bolster an ally's next ability check.",
    },
    {
      id: "mage-hand",
      name: "Mage Hand",
      level: 0,
      school: "Conjuration",
      action: "Action",
      summary: "Manifest a spectral hand for simple manipulation.",
    },
    {
      id: "healing-word",
      name: "Healing Word",
      level: 1,
      school: "Evocation",
      action: "Bonus action",
      summary: "Restore a nearby ally with a brief divine call.",
    },
    {
      id: "bless",
      name: "Bless",
      level: 1,
      school: "Enchantment",
      action: "Action",
      summary: "Empower allies' attacks and saving throws.",
    },
    {
      id: "magic-missile",
      name: "Magic Missile",
      level: 1,
      school: "Evocation",
      action: "Action",
      summary: "Launch darts of force that strike without an attack roll.",
    },
    {
      id: "shield",
      name: "Shield",
      level: 1,
      school: "Abjuration",
      action: "Reaction",
      summary: "Raise a sudden arcane guard against danger.",
    },
  ],
  items: starterItems,
};
