import { afterEach,beforeEach,describe,expect,it } from "vitest";
import { mkdtempSync,rmSync } from "node:fs";import { tmpdir } from "node:os";import path from "node:path";
import { closeDb,getDb } from "@/lib/db";import { createCampaign,joinCampaign,syncCampaign } from "@/lib/campaignStore";import { createCharacter } from "@/lib/vaultStore";import { characterInput } from "./fixtures/character";
import { createCreature,createEncounter,createHandout,createJournalEntry,endSession,getPlayerMemory,listCreatures,listJournal,publishSessionSummary,scheduleSessions,shareHandout,startEncounter,startSession,updateEncounterRun } from "@/lib/dmToolsStore";

let dataDir="";beforeEach(()=>{closeDb();dataDir=mkdtempSync(path.join(tmpdir(),"forge-dm-tools-"));process.env.FORGE_VAULT_DIR=dataDir;const now=new Date().toISOString();getDb().prepare("INSERT INTO users(id,name,email,password_hash,created_at)VALUES(?,?,?,?,?)").run("dm","DM","dm@x.test","x",now);getDb().prepare("INSERT INTO users(id,name,email,password_hash,created_at)VALUES(?,?,?,?,?)").run("player","Player","player@x.test","x",now);});afterEach(()=>{closeDb();rmSync(dataDir,{recursive:true,force:true});delete process.env.FORGE_VAULT_DIR;});

describe("pre-session DM tools store",()=>{
  it("preserves ownership, snapshots encounters, and projects campaign memory",async()=>{const character=await createCharacter("player",characterInput("Pip"));const campaign=createCampaign("dm","Prep Table");joinCampaign("player",campaign.code,character.id);
    const creature=createCreature("dm",{name:"Ash Hound",kind:"custom",armorClass:13,hitPoints:{average:18,formula:"3d8+3"},challengeRating:1,experienceValue:200,tags:["beast"],environments:["forest"],privateNotes:"Secret weakness"},campaign.id);
    expect(()=>createCreature("player",{name:"Leak",armorClass:10,hitPoints:{average:1}},campaign.id)).toThrow("Only the DM");expect(listCreatures("player",{campaignId:campaign.id}).creatures.find((item)=>item.id===creature.id)?.privateNotes).toBeUndefined();
    const handout=createHandout(campaign.id,"dm",{title:"Old Letter",category:"letter",assetType:"text",body:"Meet at midnight",privateNotes:"The seal is forged"});shareHandout(campaign.id,"dm",handout.id);
    createJournalEntry(campaign.id,"dm",{title:"Hidden plot",type:"lore",body:"Secret",visibility:"dm-private"});createJournalEntry(campaign.id,"dm",{title:"Known ally",type:"npc",body:"Mira helped the party",visibility:"players"});expect(listJournal(campaign.id,"player").map((item)=>item.title)).toEqual(["Known ally"]);
    const encounter=createEncounter("dm",{name:"Hounds at dusk",status:"ready",origin:"manual",combatants:[{id:"t",creatureId:creature.id,name:"Ash Hound",quantity:2,kind:"enemy",startingHpMode:"average",initiativeMode:"group",hidden:true},{id:"reinforcement",creatureId:creature.id,name:"Ash Hound Alpha",quantity:1,kind:"enemy",startingHpMode:"average",initiativeMode:"individual",hidden:false,waveId:"wave-2"}],waves:[{id:"wave-2",name:"The alpha arrives",trigger:{type:"round-start",round:2},combatantIds:["reinforcement"]}],reminders:[{id:"r",label:"Howl",trigger:{type:"round-start",round:2},repeat:false,completed:false}],handoutIds:[handout.id],privateNotes:"Do not leak"},campaign.id);
    const session=startSession(campaign.id,"dm",{title:"Night Road"});const run=startEncounter("dm",encounter.id);expect(run.snapshot.name).toBe("Hounds at dusk");expect(syncCampaign(campaign.id,"player").initiative.data.combatants).toHaveLength(0);expect(syncCampaign(campaign.id,"dm").initiative.data.combatants).toHaveLength(2);expect(updateEncounterRun(campaign.id,"dm",run.id,{action:"pause"})).toMatchObject({status:"paused"});expect(updateEncounterRun(campaign.id,"dm",run.id,{action:"resume"})).toMatchObject({status:"active"});
    const activated=updateEncounterRun(campaign.id,"dm",run.id,{action:"activate-wave",waveId:"wave-2"});expect(activated).toMatchObject({ok:true,activatedWaveIds:["wave-2"]});expect(syncCampaign(campaign.id,"dm").initiative.data.combatants).toHaveLength(3);expect(()=>updateEncounterRun(campaign.id,"dm",run.id,{action:"activate-wave",waveId:"wave-2"})).toThrow("already active");
    const completed=endSession(campaign.id,"dm",session.id);expect(completed.summaryDraft?.title).toBe("Night Road");const published=publishSessionSummary(campaign.id,"dm",session.id);expect(published.visibility).toBe("players");const memory=getPlayerMemory(campaign.id,"player");expect(memory.handouts[0]).not.toHaveProperty("privateNotes");expect(memory.journal.map((item)=>item.title)).toEqual(expect.arrayContaining(["Known ally","Night Road"]));
  });
  it("creates a validated recurring session series",()=>{const campaign=createCampaign("dm","Weekly Table");const dates=[3,10,17].map((days)=>new Date(Date.now()+days*24*60*60*1000).toISOString());const series=scheduleSessions(campaign.id,"dm",{title:"Weekly table",scheduledAts:dates,durationMinutes:180,location:"The Table"});expect(series).toHaveLength(3);expect(series.map((session)=>session.title)).toEqual(["Weekly table · Session 1","Weekly table · Session 2","Weekly table · Session 3"]);expect(series.every((session)=>session.status==="scheduled")).toBe(true);expect(()=>scheduleSessions(campaign.id,"dm",{scheduledAts:[dates[0],dates[0]]})).toThrow("different date");});
});
