import { afterEach,beforeEach,describe,expect,it } from "vitest";
import { mkdtempSync,rmSync } from "node:fs";import { tmpdir } from "node:os";import path from "node:path";
import { closeDb,getDb } from "@/lib/db";import { signToken,SESSION_COOKIE_NAME } from "@/lib/auth";import { createCampaign,joinCampaign } from "@/lib/campaignStore";import { createCharacter } from "@/lib/vaultStore";import { characterInput } from "./fixtures/character";import { createJournalEntry } from "@/lib/dmToolsStore";
import { POST as CREATE_CREATURE } from "@/app/api/creatures/route";import { POST as CREATE_ENCOUNTER } from "@/app/api/encounters/route";import { POST as START_ENCOUNTER } from "@/app/api/encounters/[id]/start/route";import { GET as MEMORY } from "@/app/api/campaigns/[id]/memory/route";

let dataDir="";let dmCookie="",playerCookie="",campaignId="";
beforeEach(async()=>{closeDb();dataDir=mkdtempSync(path.join(tmpdir(),"forge-dm-api-"));process.env.FORGE_VAULT_DIR=dataDir;process.env.JWT_SECRET="dm-tools-api-secret-dm-tools-api-secret";const now=new Date().toISOString();getDb().prepare("INSERT INTO users(id,name,email,password_hash,created_at)VALUES(?,?,?,?,?)").run("dm","DM","dm@api.test","x",now);getDb().prepare("INSERT INTO users(id,name,email,password_hash,created_at)VALUES(?,?,?,?,?)").run("player","Player","player@api.test","x",now);const character=await createCharacter("player",characterInput("Pip"));const campaign=createCampaign("dm","API Table");campaignId=campaign.id;joinCampaign("player",campaign.code,character.id);dmCookie=`${SESSION_COOKIE_NAME}=${encodeURIComponent(await signToken({userId:"dm"}))}`;playerCookie=`${SESSION_COOKIE_NAME}=${encodeURIComponent(await signToken({userId:"player"}))}`;});
afterEach(()=>{closeDb();rmSync(dataDir,{recursive:true,force:true});delete process.env.FORGE_VAULT_DIR;delete process.env.JWT_SECRET;});
const request=(url:string,cookie:string,value:unknown)=>new Request(url,{method:"POST",headers:{cookie,"Content-Type":"application/json"},body:JSON.stringify(value)});

describe("pre-session DM API",()=>{it("enforces DM writes, starts saved encounters, and projects player memory",async()=>{const denied=await CREATE_CREATURE(request("http://local/api/creatures",playerCookie,{campaignId,creature:{name:"Leak",armorClass:10,hitPoints:{average:1}}}));expect(denied.status).toBe(403);
  const created=await CREATE_CREATURE(request("http://local/api/creatures",dmCookie,{campaignId,creature:{name:"Clockwork Hound",armorClass:14,hitPoints:{average:20},challengeRating:1,experienceValue:200}}));expect(created.status).toBe(201);const creature=(await created.json()).creature;
  const encounterResponse=await CREATE_ENCOUNTER(request("http://local/api/encounters",dmCookie,{campaignId,encounter:{name:"Workshop Ambush",status:"ready",origin:"manual",combatants:[{id:"c",creatureId:creature.id,name:creature.name,quantity:1,kind:"enemy",startingHpMode:"average",initiativeMode:"roll",hidden:true}],reminders:[],handoutIds:[],privateNotes:"DM only"}}));expect(encounterResponse.status).toBe(201);const encounter=(await encounterResponse.json()).encounter;
  const start=await START_ENCOUNTER(request(`http://local/api/encounters/${encounter.id}/start`,dmCookie,{}),{params:Promise.resolve({id:encounter.id})});expect(start.status).toBe(201);
  createJournalEntry(campaignId,"dm",{title:"Secret",body:"No players",visibility:"dm-private"});createJournalEntry(campaignId,"dm",{title:"Recap",body:"Players know this",visibility:"players",type:"session"});const memory=await MEMORY(new Request(`http://local/api/campaigns/${campaignId}/memory`,{headers:{cookie:playerCookie}}),{params:Promise.resolve({id:campaignId})});expect(memory.status).toBe(200);expect((await memory.json()).journal.map((item:{title:string})=>item.title)).toEqual(["Recap"]);
});});
