import { randomUUID } from "node:crypto";
import { getDb } from "@/lib/db";
import type { CampaignNpc, CampaignScene } from "@/types/dmTools";

function requireDm(campaignId: string, userId: string) {
  const row = getDb().prepare("SELECT dm_user_id FROM campaigns WHERE id=?").get(campaignId) as { dm_user_id: string } | undefined;
  if (!row) throw new Error("Campaign not found.");
  if (row.dm_user_id !== userId) throw new Error("Only the DM can do that.");
}
const text = (value: unknown, max: number) => typeof value === "string" ? value.trim().slice(0, max) : "";
const strings = (value: unknown, max = 50) => Array.isArray(value) ? [...new Set(value.filter((item): item is string => typeof item === "string").map((item) => item.trim().slice(0, 160)).filter(Boolean))].slice(0, max) : [];

function cleanScene(campaignId: string, id: string, input: Record<string, unknown>, createdAt: string): CampaignScene {
  const title = text(input.title, 120); if (!title) throw new Error("Scene title is required.");
  const updatedAt = new Date().toISOString();
  return { id, campaignId, title, ...(text(input.description, 2000) ? { description: text(input.description, 2000) } : {}), ...(text(input.readAloud, 2000) ? { readAloud: text(input.readAloud, 2000) } : {}), presentUserIds: strings(input.presentUserIds), npcIds: strings(input.npcIds), objectives: strings(input.objectives), completedObjectives: strings(input.completedObjectives), clues: strings(input.clues), revealedClues: strings(input.revealedClues), handoutIds: strings(input.handoutIds), ...(text(input.privateNotes, 4000) ? { privateNotes: text(input.privateNotes, 4000) } : {}), likelyChecks: strings(input.likelyChecks), ...(text(input.linkedLocation, 160) ? { linkedLocation: text(input.linkedLocation, 160) } : {}), ...(text(input.linkedEncounterId, 80) ? { linkedEncounterId: text(input.linkedEncounterId, 80) } : {}), active: input.active === true, createdAt, updatedAt };
}

function cleanNpc(campaignId: string, id: string, input: Record<string, unknown>, createdAt: string): CampaignNpc {
  const name = text(input.name, 120); if (!name) throw new Error("NPC name is required.");
  const bounded = (value: unknown, min: number, max: number) => typeof value === "number" && Number.isFinite(value) ? Math.max(min, Math.min(max, Math.trunc(value))) : undefined;
  return { id, campaignId, name, attitude: text(input.attitude, 80) || "Neutral", ...(text(input.voice, 300) ? { voice: text(input.voice, 300) } : {}), ...(text(input.goal, 1000) ? { goal: text(input.goal, 1000) } : {}), ...(text(input.knows, 2000) ? { knows: text(input.knows, 2000) } : {}), ...(text(input.revealCondition, 1000) ? { revealCondition: text(input.revealCondition, 1000) } : {}), ...(bounded(input.armorClass, 0, 99) !== undefined ? { armorClass: bounded(input.armorClass, 0, 99) } : {}), ...(bounded(input.currentHp, 0, 9999) !== undefined ? { currentHp: bounded(input.currentHp, 0, 9999) } : {}), ...(bounded(input.maxHp, 1, 9999) !== undefined ? { maxHp: bounded(input.maxHp, 1, 9999) } : {}), ...(bounded(input.insightDc, 1, 40) !== undefined ? { insightDc: bounded(input.insightDc, 1, 40) } : {}), ...(text(input.portraitUrl, 500) ? { portraitUrl: text(input.portraitUrl, 500) } : {}), status: input.status === "dead" || input.status === "missing" ? input.status : "alive", disposition: input.disposition === "allied" || input.disposition === "hostile" ? input.disposition : "neutral", ...(text(input.lastLocation, 160) ? { lastLocation: text(input.lastLocation, 160) } : {}), ...(text(input.relationshipNotes, 2000) ? { relationshipNotes: text(input.relationshipNotes, 2000) } : {}), revealedSecrets: strings(input.revealedSecrets), ...(text(input.currentSceneId, 80) ? { currentSceneId: text(input.currentSceneId, 80) } : {}), ...(text(input.linkedJournalEntryId, 80) ? { linkedJournalEntryId: text(input.linkedJournalEntryId, 80) } : {}), createdAt, updatedAt: new Date().toISOString() };
}

export function listScenes(campaignId: string, userId: string) { requireDm(campaignId, userId); return (getDb().prepare("SELECT data FROM campaign_scenes WHERE campaign_id=? ORDER BY active DESC,updated_at DESC").all(campaignId) as Array<{ data: string }>).map((row) => JSON.parse(row.data) as CampaignScene); }
export function createScene(campaignId: string, userId: string, input: unknown) { requireDm(campaignId, userId); const id=randomUUID(),now=new Date().toISOString(),scene=cleanScene(campaignId,id,input as Record<string,unknown>,now); const db=getDb(); if(scene.active)db.prepare("UPDATE campaign_scenes SET active=0 WHERE campaign_id=?").run(campaignId);db.prepare("INSERT INTO campaign_scenes(id,campaign_id,data,active,created_at,updated_at)VALUES(?,?,?,?,?,?)").run(id,campaignId,JSON.stringify(scene),Number(scene.active),now,scene.updatedAt);return scene; }
export function updateScene(campaignId:string,userId:string,id:string,input:unknown){requireDm(campaignId,userId);const row=getDb().prepare("SELECT data,created_at FROM campaign_scenes WHERE id=? AND campaign_id=?").get(id,campaignId) as {data:string;created_at:string}|undefined;if(!row)throw new Error("Scene not found.");const scene=cleanScene(campaignId,id,{...JSON.parse(row.data),...(input as Record<string,unknown>)},row.created_at);const db=getDb();if(scene.active)db.prepare("UPDATE campaign_scenes SET active=0 WHERE campaign_id=?").run(campaignId);db.prepare("UPDATE campaign_scenes SET data=?,active=?,updated_at=? WHERE id=?").run(JSON.stringify(scene),Number(scene.active),scene.updatedAt,id);return scene;}
export function listNpcs(campaignId:string,userId:string){requireDm(campaignId,userId);return (getDb().prepare("SELECT data FROM campaign_npcs WHERE campaign_id=? ORDER BY updated_at DESC").all(campaignId) as Array<{data:string}>).map((row)=>JSON.parse(row.data) as CampaignNpc);}
export function createNpc(campaignId:string,userId:string,input:unknown){requireDm(campaignId,userId);const id=randomUUID(),now=new Date().toISOString(),npc=cleanNpc(campaignId,id,input as Record<string,unknown>,now);getDb().prepare("INSERT INTO campaign_npcs(id,campaign_id,data,created_at,updated_at)VALUES(?,?,?,?,?)").run(id,campaignId,JSON.stringify(npc),now,npc.updatedAt);return npc;}
export function updateNpc(campaignId:string,userId:string,id:string,input:unknown){requireDm(campaignId,userId);const row=getDb().prepare("SELECT data,created_at FROM campaign_npcs WHERE id=? AND campaign_id=?").get(id,campaignId) as {data:string;created_at:string}|undefined;if(!row)throw new Error("NPC not found.");const npc=cleanNpc(campaignId,id,{...JSON.parse(row.data),...(input as Record<string,unknown>)},row.created_at);getDb().prepare("UPDATE campaign_npcs SET data=?,updated_at=? WHERE id=?").run(JSON.stringify(npc),npc.updatedAt,id);return npc;}
