import type { PortraitOption } from "./portraits";

/**
 * Generated by `npm run portraits:sync`.
 * Drop source images into assets/portraits/; do not edit this file by hand.
 */
export const GENERATED_PORTRAITS: readonly PortraitOption[] = [
  { id: "portrait-auto-1947d44b-78a4-4f0f-806f-94e2e8172a35-bd24213b", src: "/portraits/drop-ins/1947d44b-78a4-4f0f-806f-94e2e8172a35-bd24213b.webp", suggestedAncestries: [] },
  { id: "portrait-auto-24ccea8b-4936-4259-a286-b33ca8f922ff-2ec12a75", src: "/portraits/drop-ins/24ccea8b-4936-4259-a286-b33ca8f922ff-2ec12a75.webp", suggestedAncestries: [] },
  { id: "portrait-auto-59798a4e-44b4-4e57-bcfa-f7ab98a69a3e-e1185807", src: "/portraits/drop-ins/59798a4e-44b4-4e57-bcfa-f7ab98a69a3e-e1185807.webp", suggestedAncestries: [] },
  { id: "portrait-auto-627e1fc9-f3b0-4c96-97ac-4a665fc14519-3d5656f4", src: "/portraits/drop-ins/627e1fc9-f3b0-4c96-97ac-4a665fc14519-3d5656f4.webp", suggestedAncestries: [] },
  { id: "portrait-auto-65c5a20c-1f33-49b4-89d1-9ec45436a5a5-e4bfde51", src: "/portraits/drop-ins/65c5a20c-1f33-49b4-89d1-9ec45436a5a5-e4bfde51.webp", suggestedAncestries: [] },
  { id: "portrait-auto-8caf03ec-f6ef-4a63-8dac-cab7caa42b94-91348dce", src: "/portraits/drop-ins/8caf03ec-f6ef-4a63-8dac-cab7caa42b94-91348dce.webp", suggestedAncestries: [] },
  { id: "portrait-auto-9135165c-34d1-477d-bca3-9a0024f5dfa7-81062148", src: "/portraits/drop-ins/9135165c-34d1-477d-bca3-9a0024f5dfa7-81062148.webp", suggestedAncestries: [] },
  { id: "portrait-auto-94c59a90-07f9-4bca-b9db-e30482bf9de5-f9bdbcc4", src: "/portraits/drop-ins/94c59a90-07f9-4bca-b9db-e30482bf9de5-f9bdbcc4.webp", suggestedAncestries: [] },
  { id: "portrait-auto-9844ffac-8288-427a-9246-7ef1e22f4367-23321203", src: "/portraits/drop-ins/9844ffac-8288-427a-9246-7ef1e22f4367-23321203.webp", suggestedAncestries: [] },
  { id: "portrait-auto-9c783519-ab63-40a6-a781-205516a8b76d-4c9886cd", src: "/portraits/drop-ins/9c783519-ab63-40a6-a781-205516a8b76d-4c9886cd.webp", suggestedAncestries: [] },
];
